name: Perform pre-release tasks
on:
  push:
    branches:
      - dev

concurrency:
  group: environment-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Latest
        uses: actions/checkout@v2

      - name: Set Up Node 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-dev-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dev-

      - name: Install Dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit
  promote-to-production:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dev
          title: Production Release
          body: Production release
