name: Automated Production release pull request
on:
  push:
    branches:
      - dev
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dev
          title: Production Release
          body: Production release
