name: Run Unit Tests

on:
  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:
    inputs:
      runAll:
        description: Run all jobs
        type: boolean
        required: false
        default: false

concurrency:
  group: environment-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_cube_unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Latest
        uses: actions/checkout@v2

      - name: Set Up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: |
            packages/cube/node_modules
          key: ${{ runner.os }}-dev-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dev-

      - name: Install Dependencies
        run: npm run install --frozen-lockfile

      - name: Run unit tests
        run: npm run test:unit
